<div class="client-brief-box">
    <p class="question">Do you have your own domain?</p>
    <p class="answer">{{ $siteBrief->present()->hasDomain() }}</p>
    <p class="question">Your domain (what you have or want)</p>
    <p class="answer">{{ $siteBrief->domain_name }}</p>
    <p class="question">Do you have your own hosting?</p>
    <p class="answer">{{ $siteBrief->present()->hasHosting() }}</p>
    <p class="question">Can you describe your current/intended hosting setup?</p>
    <p class="answer">{{ $siteBrief->hosting_details }}</p>
    <p class="question">What type of website would you like developed?</p>
    <p class="answer">{{ $siteBrief->sitetype }}</p>
    <p class="question">Additional details on the type of site:</p>
    <p class="answer">{{ $siteBrief->sitetype_details }}</p>
    <p class="question">How would you like to manage the sites content?</p>
    <p class="answer">{{ $siteBrief->content_management }}</p>
    <p class="question">Additional details on content management:</p>
    <p class="answer">{{ $siteBrief->cm_details }}</p>
    <p class="question">What social media interaction would you like on the site?</p>
    <p class="answer">{{ $siteBrief->socialmedia }}</p>
    <p class="question">What are the definite requirements for the site?</p>
    <p class="answer">{{ $siteBrief->site_requirements }}</p>
    <p class="question">Is there a certain direction you want the site to go?</p>
    <p class="answer">{{ $siteBrief->site_direction }}</p>
    <p class="question">What is the target market and average user of your site?</p>
    <p class="answer">{{ $siteBrief->sitetarget }}</p>
</div>